### ISSUE TITLE
can't build xxx-softmmu

### ISSUE THREAD

**Issue by manba-bryant** [eurecom-s3/symqemu#52] opened 2024-03-21 09:13 UTC
i can't build x86_64-softmmu，here is some question report:
![20240321-171040](https://github.com/eurecom-s3/symqemu/assets/90821399/7025f310-44d2-4f81-b82e-dd307a5802e7)
![20240321-171131](https://github.com/eurecom-s3/symqemu/assets/90821399/eb5b77ff-06ef-4348-ac5a-41f2a114b1ee)

how can i resolve this question? or can u show me the way to build x86_64/arm-softmmu? Thanks anyway!

**Comment by manba-bryant** [comment] 2024-03-21 09:29
the building command is : ../configure                                                    \
      --audio-drv-list=                                           \
      --disable-sdl                                               \
      --disable-gtk                                               \
      --disable-vte                                               \
      --disable-opengl                                            \
      --disable-virglrenderer                                     \
      --disable-werror                                            \
      --target-list=arm-softmmu                             \
      --symcc-source=../symcc                                     \
      --symcc-build=../symcc/build

**Comment by aurelf** [comment] 2024-03-21 10:18
"arm-softmmu" refers to the system mode (vs the user mode).  
System mode isn't supported for now, this needs more work to be supported. 
We have a prototype of this and will integrate this in the public version at some point but it needs more work.  See Issue #32 

Closing  as duplicate of  #32

**Comment by aurelf** [comment] 2024-03-21 10:21
Duplicate of  #32

**Closed by aurelf** 2024-03-21 10:21 UTC

**Comment by aurelf** [comment] 2024-03-21 10:22
Github seems to be unable to register this as a duplicate :man_shrugging:

**Comment by manba-bryant** [comment] 2024-03-21 15:35
Thank you so much!
