### ISSUE TITLE
[Feature] MIPS full-system mode

### ISSUE THREAD

**Issue by zhangzheng18** [eurecom-s3/symqemu#47] opened 2024-03-12 09:09 UTC
Dear author,
You have developed a great tool, now I want to use this to do the whole system simulation of MIPS architecture, does this tool support this function?

**Comment by aurelf** [comment] 2024-03-12 10:23
Hi, not for now. 
This requires two parts:
1) supporting MIPS, 
MIPS user mode should already be supported (see #17 in case of need) and submit a bug with a test case if that doesn't work.

2) supporting system mode: duplicate of #32 
We have plans to push the system support (we have a prototype, but it needs some work to be imported here).  
Please track issue #32

**Closed by aurelf** 2024-03-12 10:23 UTC
Labels: enhancement
